name: ai_trivia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  flutter_riverpod: ^2.3.6
  iconsax: ^0.0.8
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.8.4
  go_router: ^9.0.3
  overlay_support: ^2.1.0
  flex_color_scheme: ^7.1.2
  get_it: ^7.6.0
  dio: ^5.3.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
